### PR TITLE
GUACAMOLE-662: Fix handling of unit tests within build.

### PR DESCRIPTION
**Pull request by mike-jumper**
This change corrects the way unit tests are handled within the guacamole-server build, logging the correct number of tests/passes/failures and failing the build overall if at least one test fails.

This required:

* Removing a ton of boilerplate C test runners, replacing them with generated code (see `util/generate-test-runner.pl` and `README-unit-testing.md` within these changes)
* Refactoring existing tests to leverage `util/generate-test-runner.pl`, taking the opportunity to clean up and reorganize accordingly.
* Fixing the way several of these tests `fork()` - parent/child logic was switched, resulting in race conditions in logging of test results.

The new `util/generate-test-runner.pl` script allows unit tests to be written as simple function declarations following conventions documented in `README-unit-testing.md`. So long as those conventions are followed, only the test functions themselves are required, and the necessary boilerplate to actually run those functions, collect results, etc. is generated automatically.

**NOTE:** Merging these changes will likely result in the build failing within CI when `make check` is run. This is actually a Good Thing, as the build really should have been failing all this time due to [GUACAMOLE-510](https://issues.apache.org/jira/browse/GUACAMOLE-510).

### CODE REVIEW

**Comment by mike-jumper** [comment]
For reference, the incorrect test handling of the current build produces the following erroneous report:

```
[mjumper@dev-mjumper guacamole-server]$ make check
...
PASS: test_libguac
============================================================================
Testsuite summary for guacamole-server 1.0.0
============================================================================
# TOTAL: 1
# PASS:  1
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================
...
make[1]: Leaving directory '/home/mjumper/apache/guacamole/guacamole-server'
[mjumper@dev-mjumper guacamole-server]$ 
```

There is actually more than one test, and one of those tests (the nested socket test) is actually failing. With these changes in place, the report reflects the status of each test:

```
[mjumper@dev-mjumper guacamole-server]$ make check
...
make[4]: Entering directory '/home/mjumper/apache/guacamole/guacamole-server/src/libguac/tests'
PASS: test_libguac 1 - [pool] next_free: OK
PASS: test_libguac 2 - [client] buffer_pool: OK
PASS: test_libguac 3 - [client] layer_pool: OK
PASS: test_libguac 4 - [parser] append: OK
PASS: test_libguac 5 - [parser] read: OK
PASS: test_libguac 6 - [socket] fd_send_instruction: OK
FAIL: test_libguac 7 - [socket] nested_send_instruction: Assertion failed on socket/nested_send_instruction.c:105: CU_ASSERT_EQUAL(offset,strlen(expected))
PASS: test_libguac 8 - [unicode] utf8_charsize: OK
PASS: test_libguac 9 - [unicode] utf8_read: OK
PASS: test_libguac 10 - [unicode] utf8_strlen: OK
PASS: test_libguac 11 - [unicode] utf8_write: OK
PASS: test_libguac 12 - [protocol] decode_base64: OK
============================================================================
Testsuite summary for guacamole-server 1.0.0
============================================================================
# TOTAL: 12
# PASS:  11
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0
============================================================================
See src/libguac/tests/test-suite.log
============================================================================
make[4]: *** [Makefile:1032: test-suite.log] Error 1
make[4]: Leaving directory '/home/mjumper/apache/guacamole/guacamole-server/src/libguac/tests'
make[3]: *** [Makefile:1140: check-TESTS] Error 2
make[3]: Leaving directory '/home/mjumper/apache/guacamole/guacamole-server/src/libguac/tests'
make[2]: *** [Makefile:1211: check-am] Error 2
make[2]: Leaving directory '/home/mjumper/apache/guacamole/guacamole-server/src/libguac/tests'
make[1]: *** [Makefile:879: check-recursive] Error 1
make[1]: Leaving directory '/home/mjumper/apache/guacamole/guacamole-server/src/libguac'
make: *** [Makefile:527: check-recursive] Error 1
[mjumper@dev-mjumper guacamole-server]$ 
```

The boilerplate I refer to are files like [`tests/test_libguac.c`](https://github.com/apache/guacamole-server/blob/0d435e243579f15c84ddca1d44bbb33c7269e39a/tests/test_libguac.c) and [`tests/protocol/suite.c`](https://github.com/apache/guacamole-server/blob/master/tests/protocol/suite.c) which do nothing but register test functions with CUnit and request that CUnit run all tests. These changes remove the need to manually define such boilerplate, reducing the burden of writing guacamole-server unit tests to the tests themselves.

**Comment by mike-jumper** [comment]
I'll recheck. If things are building, though, this looks more like an issue with linking than with having the wrong version. Was the devel package for CUnit present when `./configure` was run?

**Comment by necouchman** [comment]
Maybe it was my build environment.  Went back and did a `make distclean` followed by `./configure`, `make -j5`, and `make check` and I no longer get the errors above.  Now, instead, I get this:

    PASS: test_libguac 1 - [protocol] decode_base64: OK
    PASS: test_libguac 2 - [client] buffer_pool: OK
    PASS: test_libguac 3 - [client] layer_pool: OK
    PASS: test_libguac 4 - [unicode] utf8_charsize: OK
    PASS: test_libguac 5 - [unicode] utf8_read: OK
    PASS: test_libguac 6 - [unicode] utf8_strlen: OK
    PASS: test_libguac 7 - [unicode] utf8_write: OK
    PASS: test_libguac 8 - [pool] next_free: OK
    PASS: test_libguac 9 - [parser] append: OK
    PASS: test_libguac 10 - [parser] read: OK
    PASS: test_libguac 11 - [socket] fd_send_instruction: OK
    FAIL: test_libguac 12 - [socket] nested_send_instruction: Assertion failed on socket/nested_send_instruction.c:105: CU_ASSERT_EQUAL(offset,strlen(expected))

(Full Output: https://pastebin.com/RLSpPWra)

**Comment by necouchman** [comment]
Aha.  Okay, will go ahead and merge these changes.

**Comment by necouchman** [comment]
Oops...I think your changes to the .gitignore file, here, were a little over-zealous:

    nick@linux-i0lj:~/guacamole/guacamole-server> git status
    On branch master
    Your branch is up-to-date with 'origin/master'.
    Untracked files:
      (use "git add <file>..." to include in what will be committed)
    
	    config.guess
	    config.sub
	    depcomp
	    install-sh
	    ltmain.sh
	    missing
	    test-driver

    nothing added to commit but untracked files present (use "git add" to track)

Unless you intended to not exclude those anymore?

**Comment by necouchman** [comment]
Ah, okay, looks good.

**Pull request merged**
