### PR TITLE
GUACAMOLE-1875: Check return values of WebP API functions.

### PR DESCRIPTION
**Pull request by vrabaud**
Those will be made nodiscard at some point anyway.
Issue GUACAMOLE-1875

### CODE REVIEW

**Comment by necouchman** [comment]
Thanks @vrabaud. Please open a Jira ticket (you may need to request an account, if you don't already have one) for this and tag the Jira ticket number (GUACAMOLE-XXXX:) in both the PR and the commit messages.

https://guacamole.apache.org/open-source/

**Comment by vrabaud** [comment]
It says it will take days to create an account.
Why do I have to be the one to create a ticket? Anyway, let's wait then.

**Comment by vrabaud** [comment]
I rebased as the CI error was unrelated. Maybe it got fixed at HEAD.

**Comment by necouchman** [comment]
> I rebased as the CI error was unrelated. Maybe it got fixed at HEAD.

Yes, there was an issue causing build failures that is now fixed.

Also, I see that you got the account and opened the ticket - please update Pull Request with GUACAMOLE-XXXX: prefix, along with commit requests.

Thanks!!

**Comment by vrabaud** [comment]
Done

**Review by necouchman — APPROVED** [review]

**Pull request merged**
