### PR TITLE
GUACAMOLE-1312: Adds Canadian French keymaps

### PR DESCRIPTION
**Pull request by webtroter**
This is from kavenr.

I hope this is the only thing that needs to be updated.

I didnt find those files in my container, so I could change them to test. Maybe I didnt check at the right places.

I can confirm the keymap is correct.

### CODE REVIEW

**Review by necouchman — APPROVED** [review]
Overall looks okay to me - @mike-jumper or @jmuehlner any concerns?

@webtroter You will need to add the keyboard map on the guacamole-client so that it is an option within the connection parameters, but it's a relatively simple change - just an update to the `rdp.json` file to add it as an option, and then updating the related translation json files.

**Comment by webtroter** [comment]
Is everything OK ?

Are we only waiting on a second opinion?

I can`t wait to be able to use the correct characters, like the interrogation marks ;)

**Comment by necouchman** [comment]
@webtroter Only thing is that the commit message needs to be updated with the GUACAMOLE-1312: prefix.

**Comment by webtroter** [comment]
@necouchman : Done :)

**Comment by mike-jumper** [comment]
> Overall looks okay to me - @mike-jumper or @jmuehlner any concerns?

Nothing from me. I did not compare against a Canadian keyboard, but the mapping looks sane.

**Comment by webtroter** [comment]
If needed, I can a picture of a canadian French keyboard. I have one next to me sometimes.

**Pull request merged**
