### PR TITLE
GUACAMOLE-572: Fix typo from "test-based protocol" to "text-based protocol"

### PR DESCRIPTION
**Pull request by eesheesh**

### CODE REVIEW

**Comment by mike-jumper** [comment]
Please see our [contribution guidelines](https://github.com/apache/guacamole-client/blob/984ab48ce8dbbb5b9949ce1f5e5f774168b4830b/CONTRIBUTING). Specifically:

* All changes must have an associated JIRA issue. It does not matter how small the change may be, or if the change is documentation only. All changes must be tracked in JIRA, with the JIRA issue providing a description of the nature of the issue being addressed.
* Commit messages need to tag the associated JIRA issue (you can see examples of this in our git history) and describe at a high-level the change being made. If you can think of a better high-level description for your changes than simply "Fix typo", please do.

**Comment by necouchman** [comment]
> so if you can't change the commit message on merge, let me know and I'll create a new PR with a whole new commit for this.

You can change the commit message by rebasing the commits and then doing a force push.  You'd do something like:
- git rebase -i <hash of commit right before yours> and then choose the "reword" option for the commit.
- Finish the rebase
- "git push -f" to force the push to the remote repo

**Comment by eesheesh** [comment]
To do that I'd need to clone the entire repo to disk and I'm not planning to do that for a one-character documentation fix. :) I'd like to stick to the web interface. Sorry if this causes any headaches!

**Comment by necouchman** [comment]
> I'd like to stick to the web interface. Sorry if this causes any headaches!

Ah, I see.  Understood - no, as long as you close this one out and don't leave it hanging open, it's fine to close it and open another one.

**Pull request closed without merging**
