### PR TITLE
GUACAMOLE-1114: Fix the destruction of some thread mutexes

### PR DESCRIPTION
**Pull request by myjimmy**
I have fixed the GUACAMOLE-1114 issue.

### CODE REVIEW

**Comment by myjimmy** [comment]
> Looks good. Thanks @myjimmy!

@necouchman My pleasure!

**Comment by myjimmy** [comment]
> Actually, before merging this, could you adjust the commit messages a bit? They're very long and are "wrapping" around to multiple lines with the "..." that git inserts by default. If you could make these a little shorter - something like:
> Clean up print job mutex lock
> Clean up clipboard mutex lock
> 
> That would be great.

OK. I'll adjust my commits.

**Comment by myjimmy** [comment]
@necouchman Could you let me know how to modify the submitted pull request?

**Comment by necouchman** [comment]
@myjimmy: You just push changes to your current branch - so, if you want to modify the commit messages, you'd go back and do:
```git rebase -i <COMMIT BEFORE YOUR COMMIT>```

and when you get prompted for the commits, use the "reword" option (r) to edit the commit messages.  Once the rebase is done, do:
```git push -f```

and the changes will show up, here.

**Comment by myjimmy** [comment]
> @myjimmy: You just push changes to your current branch - so, if you want to modify the commit messages, you'd go back and do:
> `git rebase -i <COMMIT BEFORE YOUR COMMIT>`
> 
> and when you get prompted for the commits, use the "reword" option (r) to edit the commit messages. Once the rebase is done, do:
> `git push -f`
> 
> and the changes will show up, here.

@necouchman: Thanks. I have just modified the comments.

**Pull request merged**
